image: node:18

stages:
  - build

cache:
  paths:
    - node_modules/

before_script:
  - npm ci
  - npm install -g vitepress

build-docs:
  stage: build
  script:
    - npm run docs:build -- --host
    - mv docs/.vitepress/dist public
  artifacts:
    paths:
      - public
  only:
    - main
