services:
  webdocs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/usr/src/app  # mounted cd container
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "docs:dev", "--", "--host"] # ovveriding dockerfile

# to run the container
# docker-compose up --build

